import 'dart:math';

import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:to_ryu_mon_2024/page/to_ryu_mon_page.dart';
import 'package:to_ryu_mon_2024/stroke_page_transition.dart';
import 'package:to_ryu_mon_2024/util.dart';
import 'package:to_ryu_mon_2024/view/area_restrict_view.dart';

class StartPage extends StatelessWidget {
  const StartPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.black,
        body: AreaRestrictView(
          child: Stack(
            children: [
              Positioned.fill(
                child: Opacity(
                  opacity: 0.4,
                  child: Image.asset("assets/images/start.webp",
                      fit: BoxFit.cover),
                ),
              ),
              const Align(
                alignment: Alignment.bottomLeft,
                child: Padding(
                  padding: EdgeInsets.all(8.0),
                  child: Text(
                    "Generated by DALL-E3",
                    style: TextStyle(color: Colors.white54),
                  ),
                ),
              ),
              Align(
                alignment: Alignment.bottomCenter,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    TextButton(
                        onPressed: () {
                          navigateWithStrokeTransition(
                              context, const ToRyuMonPage());
                        },
                        child: const Padding(
                          padding: EdgeInsets.all(8.0),
                          child: Text("Start",
                              style: TextStyle(
                                  fontSize: 30,
                                  color: Colors.white70,
                                  fontWeight: FontWeight.bold)),
                        )),
                    TextButton(
                        onPressed: () {
                          FirebaseAnalytics.instance
                              .logEvent(name: "how_to_play");
                          showDialog(
                              context: context,
                              builder: (_) {
                                return AlertDialog(
                                  title: const Text("How to play"),
                                  content: const Text("鯉→タップする\n鯉以外→タップしない"),
                                  actions: [
                                    TextButton(
                                        onPressed: () {
                                          Navigator.of(context).pop();
                                        },
                                        child: const Text("OK"))
                                  ],
                                );
                              });
                        },
                        child: const Padding(
                          padding: EdgeInsets.all(8.0),
                          child: Text("How to play",
                              style: TextStyle(
                                  fontSize: 30,
                                  color: Colors.white70,
                                  fontWeight: FontWeight.bold)),
                        )),
                    const SizedBox(
                      height: 100,
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.baseline,
                      textBaseline: TextBaseline.alphabetic,
                      children: [
                        const Text(
                          "© 2024",
                          style: TextStyle(
                              color: Colors.white70,
                              fontWeight: FontWeight.bold),
                        ),
                        TextButton(
                            onPressed: () {
                              openUrl("https://twitter.com/Fastriver_org");
                            },
                            child: const Text(
                              "fastriver_org",
                              style: TextStyle(
                                  color: Colors.white70,
                                  fontWeight: FontWeight.bold),
                            )),
                        const Text(
                          "|",
                          style: TextStyle(
                              color: Colors.white70,
                              fontWeight: FontWeight.bold),
                        ),
                        TextButton(
                            onPressed: () {
                              showLicensePage(context: context);
                            },
                            child: const Text(
                              "License",
                              style: TextStyle(
                                  color: Colors.white70,
                                  fontWeight: FontWeight.bold),
                            ))
                      ],
                    ),
                    const SizedBox(
                      height: 30,
                    )
                  ],
                ),
              ),
              Align(
                alignment: Alignment.topCenter,
                child: LayoutBuilder(builder: (context, constraints) {
                  final height = constraints.biggest.height - 300;
                  return SizedBox(
                    height: max(height, 0),
                    child: Center(
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Text(
                            "登竜門",
                            style: GoogleFonts.yujiBoku(
                                color: Colors.white, fontSize: 80),
                            //style: TextStyle(color: Colors.white, fontSize: 50),
                          ),
                        ],
                      ),
                    ),
                  );
                }),
              ),
            ],
          ),
        ));
  }
}
